version: '3'
name: login
services:
  redis:
    container_name: login-redis
    image: redis:7.0.11
    ports:
      - "6379:6379"

  mysql:
    container_name: login-db
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: logindb
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    depends_on:
      - redis